- hosts: "{{ groups['masters'][0] }}"
  gather_facts: false
  tasks:
    # - name: Leave cluster
    #   shell: docker swarm leave --force
    #   register: swarm_leave
    #   ignore_errors: yes

    - name: Initialize Docker Swarm on master
      shell: docker swarm init
      register: swarm_init

    - name: Get join token for managers
      shell: docker swarm join-token manager -q
      register: master_join_token
      changed_when: false

    - name: Get join token for workers
      shell: docker swarm join-token worker -q
      register: worker_join_token
      changed_when: false

    - name: Set fact for manager join token
      set_fact:
        master_join_token: "{{ master_join_token.stdout }}"

    - name: Set fact for worker join token
      set_fact:
        worker_join_token: "{{ worker_join_token.stdout }}"

- hosts: all
  gather_facts: false
  tasks:
    # - name: Leave cluster
    #   shell: docker swarm leave --force
    #   register: swarm_leave
    #   when: inventory_hostname != groups['masters'][0]
    #   ignore_errors: yes

    - name: Join manager nodes to swarm
      shell: docker swarm join --token {{ hostvars[groups['masters'][0]].master_join_token }} {{ hostvars[groups['masters'][0]]['ansible_host'] }}:2377
      when: inventory_hostname != groups['masters'][0] and inventory_hostname in groups['masters']

    - name: Join worker nodes to swarm
      shell: docker swarm join --token {{ hostvars[groups['masters'][0]].worker_join_token }} {{ hostvars[groups['masters'][0]]['ansible_host'] }}:2377
      when: inventory_hostname in groups['workers']