- hosts: "{{ groups['managers'][0] }}"

  tasks:
    - name: Copy portainer dir
      synchronize:
        src: .
        dest: .

    - name: Add portainer label for main node
      shell: 'docker node update --label-add portainer.portainer-data=true {{ main_node }}'

    - name: Deploy portainer
      shell: 'docker stack deploy -c portainer/docker-compose.yml portainer'
      environment:
        - DOMAIN: '{{ portainer_domain }}'
      args:
        chdir: $HOME
